### ISSUE TITLE
project card hover effect

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/ui-design-system#30]

**Comment by mosaeedi** [comment]
![Screen Shot 2022-02-22 at 1.40.48 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/f13fd085-54bb-4252-8abc-0891410d12e0)

Instead of expanding the project card, I suggest expanding the content section height inside the project card, to show the buttons at the bottom.

**Comment by mosaeedi** [comment]
@markoprljic @MoeNick

**Comment by markoprljic** [comment]
Approved.
