### ISSUE TITLE
View similar projects

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/ui-design-system#31]
We need to know what we should do about _"View similar project"_!
showing inside the page or on another page?

I agree with @MoeNick to show it inside the single project page, at the bottom, but load them after loading all of the single project page content to prevent slowing the page load, and we can show a _show more_ button to get the user to the new page and list all similar projects.

![Screen Shot 2022-02-21 at 7.39.56 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/89448652-b431-48a9-affe-eb547dbaf14c)

**Comment by markoprljic** [comment]
This link should open new page in the same tab with list of similar projects.
